// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJNka4tPzd1yeYysW0RIrG38kTOqujwXk',
    appId: '1:770666017890:web:d84a520e1680fe1e6ecd3b',
    messagingSenderId: '770666017890',
    projectId: 'embarque-solidario-12881',
    authDomain: 'embarque-solidario-12881.firebaseapp.com',
    storageBucket: 'embarque-solidario-12881.appspot.com',
    measurementId: 'G-HK1EXJSJXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDilljD0G8L8TcYELZ44gV84U-0lfTizNo',
    appId: '1:770666017890:android:deb0eb3e58ab49cc6ecd3b',
    messagingSenderId: '770666017890',
    projectId: 'embarque-solidario-12881',
    storageBucket: 'embarque-solidario-12881.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3bYc35YdAcbjIOtyPcBu1e5qYCsPGYQc',
    appId: '1:770666017890:ios:83581971863bfee76ecd3b',
    messagingSenderId: '770666017890',
    projectId: 'embarque-solidario-12881',
    storageBucket: 'embarque-solidario-12881.appspot.com',
    iosClientId: '770666017890-pur6u9fa0dnjdmc35gdas75e4eae854c.apps.googleusercontent.com',
    iosBundleId: 'com.example.embarqueSolidario',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3bYc35YdAcbjIOtyPcBu1e5qYCsPGYQc',
    appId: '1:770666017890:ios:de7e6e2cf172cedb6ecd3b',
    messagingSenderId: '770666017890',
    projectId: 'embarque-solidario-12881',
    storageBucket: 'embarque-solidario-12881.appspot.com',
    iosClientId: '770666017890-a0oh4p2c4r9tetg91f9t5i91aj67e338.apps.googleusercontent.com',
    iosBundleId: 'com.example.embarqueSolidario.RunnerTests',
  );
}
